/**
 * Print-based PDF export for a portal section.
 * Opens a new window with just the section content and triggers print.
 * @param {string} title - Document title
 * @param {HTMLElement} element - The DOM element to print
 */
export function exportToPdf(title, element) {
  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow popups to export PDF.');
    return;
  }

  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1e293b; }
        h1 { font-size: 20px; margin-bottom: 8px; color: #1e3a5f; }
        h2 { font-size: 16px; margin: 16px 0 8px; color: #334155; }
        h3 { font-size: 13px; margin: 12px 0 6px; color: #475569; }
        p, td, th, li, span { font-size: 12px; line-height: 1.5; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; }
        th { background: #f1f5f9; font-weight: 600; }
        .status-complete { color: #16a34a; font-weight: 600; }
        .status-in-progress { color: #d97706; font-weight: 600; }
        .status-pending { color: #94a3b8; }
        .print-meta { color: #94a3b8; font-size: 10px; margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 8px; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <p style="color: #64748b; margin-bottom: 16px;">Exported ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
      ${element.innerHTML}
      <p class="print-meta">Generated by JMC Solutions Client Portal</p>
    </body>
    </html>
  `);
  win.document.close();
  // Small delay for content to render before print dialog
  setTimeout(() => win.print(), 300);
}
